name: Build

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3

      - name: Build
        run: bazel build --cxxopt='-std=c++17' //...

      - name: Test
        run: bazel test --cxxopt='-std=c++17' --test_output=errors  //...
